In [2]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.regression.rolling import RollingOLS
import matplotlib.pyplot as plt
import seaborn
seaborn.set_style('darkgrid')
pd.plotting.register_matplotlib_converters()
%matplotlib inline

In [3]:
test_data = pd.read_csv('/Users/baconbaker/Documents/Studium/ANM/anm-project/data/test_data/esb.csv')
train_data = pd.read_csv('/Users/baconbaker/Documents/Studium/ANM/anm-project/data/train_data/esb.csv')
train_data['start_time'] = train_data['startTime']
print(train_data.head())
print(test_data.head())

  serviceName      startTime  avg_time  num  succee_num  succee_rate  \
0     osb_001  1588521600000    0.5691  347         347          1.0
1     osb_001  1588521660000    0.5813  354         354          1.0
2     osb_001  1588521720000    0.5397  363         363          1.0
3     osb_001  1588521780000    0.6190  387         387          1.0
4     osb_001  1588521840000    0.4909  387         387          1.0

      start_time
0  1588521600000
1  1588521660000
2  1588521720000
3  1588521780000
4  1588521840000
  service_name     start_time  avg_time  num  succee_num  succee_rate
0      osb_001  1606881600000    0.6214  361         361       1.0000
1      osb_001  1606881660000    0.5861  343         343       1.0000
2      osb_001  1606881720000    5.0125  126         122       0.9683
3      osb_001  1606881780000    9.3487   70          70       1.0000
4      osb_001  1606881840000    1.4756  375         375       1.0000

In [4]:
def get_onehot(df):
    df['start_time'] = pd.to_datetime(df['start_time'], unit='ms', origin='unix')
    df = df.sort_values(by='start_time')
    df = df.set_index('start_time')
    return df

In [5]:
train_data = get_onehot(train_data)
test_data = get_onehot(test_data)

In [6]:
train_data

,serviceName,startTime,avg_time,num,succee_num,succee_rate
start_time,,,,,,
2020-05-03 16:00:00,osb_001,1588521600000,0.5691,347,347,1.0
2020-05-03 16:01:00,osb_001,1588521660000,0.5813,354,354,1.0
2020-05-03 16:02:00,osb_001,1588521720000,0.5397,363,363,1.0
2020-05-03 16:03:00,osb_001,1588521780000,0.6190,387,387,1.0
2020-05-03 16:04:00,osb_001,1588521840000,0.4909,387,387,1.0
...,...,...,...,...,...,...
2020-05-04 15:55:00,osb_001,1588607700000,0.6240,600,600,1.0
2020-05-04 15:56:00,osb_001,1588607760000,0.5897,643,643,1.0
2020-05-04 15:57:00,osb_001,1588607820000,0.6495,619,619,1.0
2020-05-04 15:58:00,osb_001,1588607880000,0.6262,614,614,1.0
2020-05-04 15:59:00,osb_001,1588607940000,0.6530,592,592,1.0

In [8]:
endog = train_data['avg_time']
exog = train_data['avg_time']

rols = RollingOLS(endog, exog, window=60)
rres = rols.fit()
params = rres.params

/Users/baconbaker/anaconda3/envs/ml/lib/python3.8/site-packages/statsmodels/regression/rolling.py:265: RuntimeWarning: divide by zero encountered in log
  llf = -np.log(ssr) * nobs2  # concentrated likelihood